[2023-12-08 10:34:59,424][__main__][INFO] - For logs, checkpoints and samples check /Volumes/Castile/HackerProj/denoiser
[2023-12-08 10:35:04,410][denoiser.solver][INFO] - ----------------------------------------------------------------------
[2023-12-08 10:35:04,411][denoiser.solver][INFO] - Training...
[2023-12-08 10:35:04,482][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 123, in main
    _main(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 116, in _main
    run(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 97, in run
    solver.train()
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/solver.py", line 140, in train
    train_loss = self._run_one_epoch(epoch)  ##########################
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/solver.py", line 203, in _run_one_epoch
    for i, data in enumerate(logprog):
                   ^^^^^^^^^^^^^^^^^^
TypeError: iter() returned non-iterator of type 'LogProgress'
